services:
  frontend:
    image: image-frontend-production:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    container_name: container-frontend-production-project
    depends_on:
      - backend
  backend:
    image: image-backend-production:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules # anonymous volume for node_modules only
    container_name: container-backend-production-project
    environment:
      - PORT=3001
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-production
    depends_on:
      - frontend
      - backend
  debug-helper:
    image: busybox
